# Generated by Django 4.1.2 on 2024-06-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='anio',
            field=models.IntegerField(),
        ),
    ]
