# Generated by Django 4.1.2 on 2024-06-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_alter_auto_anio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='id_autos',
            new_name='id_auto',
        ),
        migrations.AlterField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='producto'),
        ),
    ]
