# Generated by Django 4.1.2 on 2024-06-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0003_rename_id_autos_auto_id_auto_alter_auto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='imagen',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='auto',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
