# Generated by Django 4.1.2 on 2024-06-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0004_alter_auto_imagen_alter_auto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='imagen',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
