# Generated by Django 4.1.2 on 2024-06-30 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='usuario',
        ),
    ]
